INSERT INTO "entidades_caclase" ("nombre") VALUES
('TRX'),
('Insanity'),
('Funcional'),
('Spinning'),
('Crossfit'),
('Kick Boxing'),
('Mait Tai'),
('CX Worx'),
('Tulas'),
('Taichi'),
('Chi Kung'),
('Yoga'),
('Rumba'),
('Zumba'),
('Pilates Reformer'),
('Natación Infantil'),
('Programa Edad de Oro'),
('Abdomen Extremo'),
('Kung-Fu'),
('Circuito Marcial'),
('Strong Performance'),
('RPM'),
('Body Flow'),
('Hit'),
('Cycling'),
('Body Pump'),
('Combat'),
('Tap-Out'),
('Aerobicos'),
('Circuito'),
('Crosstech'),
('Cyclingtech Aventura'),
('Cyclingtech Desafio'),
('Cyclingtech Máximo Esfuerzo'),
('Cyclingtech Quema de Grasa'),
('Cyclingtech Terrenos Extremos'),
('Pilates Mat'),
('Danzika'),
('Bodyattack'),
('Aerotono');

INSERT INTO "entidades_caservicio" ("nombre") VALUES
('Fisioterapia'),
('Deportologo'),
('Nutricionista'),
('Psicología'),
('I.P.S'),
('Masajes y terapias'),
('Fiestas infantiles'),
('Vacaciones recreativas'),
('Escuela de futbol');