INSERT INTO entidades_tiporequerimientoreconocimientodeportivo(id, descripcion) VALUES 
    (1, 'Aceptación expresa de deportistas'),
	(2, 'Acreditación de cumplimiento de requisitos'),
	(3, 'Acta de afiliación deportistas'),
	(4, 'Acta de constitución del club'),
	(5, 'Acta de conformación del organo administrativo'),
	(6, 'Constancia de elección miembro de los dos miembros de la comisión disciplinaria'),
	(7, 'Constancia de elección del tercer miembro de la comisión disciplinaria'),
	(8, 'Constancia nombramiento del rector'),
	(9, 'Estatutos'),
	(10, 'Información de la oficina en que funcionará el club'),
	(11, 'Listados de deportistas'),
	(12, 'Reconocimiento de caracter oficial o personería jurídica'),
	(13, 'Resolución  de Afiliación de deportistas'),
	(14, 'Resolución de creación y reglamentación del club'),
	(15, 'Copia Solicitud reconocimiento deportivo por escrito'),
	(16, 'Tarjetas profesionales de los revisores fiscales'),
	(17, 'Otros');
