INSERT INTO "entidades_tiposuperficie" ("id", "descripcion") VALUES
(2,	'Cesped Natural'),
(3,	'Cesped Sintético'),
(6,	'Asfalto'),
(1,	'Tierra'),
(4,	'Polipropileno modular'),
(5,	'Madera'),
(7,	'Madera'),
(8,	'Sintética'),
(9,	'Arena'),
(10,	'Madera'),
(11,	'Sintética'),
(12,	'Madera'),
(13,	'Sintética'),
(14,	'Colchonetas'),
(15,	'Peanas'),
(16,	'Tatami'),
(17,	'Pistas'),
(18,	'Lona'),
(19,	'Poliuretano'),
(20,	'Resina Sintética'),
(21,	'Espuma de alta densidad'),
(22,	'Cerámica'),
(23,	'Agua'),
(24,	'Vidrio'),
(25,	'Hielo'),
(26,	'Mesa'),
(27,	'Arcilla'),
(28,	'Tierra'); 